.\" Redistribution and use in source and binary forms, with
.\" or without modification, are permitted provided that the
.\" following conditions are met:
.\" 
.\" 1. Redistributions of source code must retain this list
.\"    of conditions and the following disclaimer.
.\" 2. Redistributions in binary form must reproduce this
.\"    list of conditions and the following disclaimer in the
.\"    documentation and/or other materials provided with the
.\"    distribution.
.\" 
.\" THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND
.\" CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED
.\" WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
.\" WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A
.\" PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
.\" COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT,
.\" INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
.\" CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
.\" PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE,
.\" DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
.\" CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
.\" CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE
.\" OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
.\" SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH
.\" DAMAGE.
.Dd April 4, 2020
.Dt GOOC 1
.Os thtk
.Sh NAME
.Nm gooc
.Nd Crash Bandicoot game-oriented object C script compiler tool
.Sh SYNOPSIS
.Nm
.Op Fl V
.Op Fl c Ar version
.Op Fl r Ar region
.Op Fl h Ar output
.Op Fl e Ar format
.Ns Ar ...
.Op Ar input Op Ar output
.Sh DESCRIPTION
The
.Nm
utility compiles gooc scripts.
These options are accepted:
.Bl -tag -width Ds
.It Fl V
Displays the program version and exits.
.It Fl c Ar version
Compiles a script.
.It Fl r Ar region
Sets the region mode, used for time based units. "ntsc-u", "ntsc-j" and "pal" are acceptable. Defaults to "ntsc-u".
.It Fl h Ar output
Set the output path for a "header" file, which can be included in gooc scripts, and contains the resulting values of the GOOL object ID and its spawns.
.It Fl e Ar format
Set the output path
.Ar format
for external GOOL modules. For example. using format 
.Ns Ql %s.gool
and a module named 
.Ns Ql TestC
will result in an output directory of 
.Ns Ql TestC.gool
for this particular module.
.El
.Pp
Replace the
.Ar version
option by the gool script format version requested.
Running the program without a command will list the supported formats.
.Sh EXIT STATUS
The
.Nm
utility exits with 0 on success, 1 on error.
.Sh SEE ALSO
.Lk https://github.com/ManDude/thtk/tree/gooc "Project homepage"
.Sh SECURITY CONSIDERATIONS
Invalid data may not be properly handled.
Do not operate on untrusted files.
